### PR TITLE
chore: update CODEOWNERS

### PR DESCRIPTION
**Pull request by daveworth**
### CHANGES

Replace Austen Bryan and Gerred with Dave Worth as CODEOWNERS

## Checklist before merging

- [ ] Tests, documentation, ADR added or updated as needed
- [x] Followed the [Contributor Guide Steps](https://github.com/defenseunicorns/leapfrogai/blob/main/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by justinthelaw** [comment]
Nit-pick! as part of this change, can we move CODEOWNERS into the `.github/` directory to lessen the current (and soon more) root-level file count? Just to clean-up the root-level directory some more, since we have a lot there.

**Comment by daveworth** [comment]
I think that would generally be different from the majority of projects in the Defense Unicorns org - I will defer to @YrrepNoj on this suggestion.

**Comment by YrrepNoj** [comment]
While I love a clean root directory I think CODEOWNERS is an important file and should stay at the root 🫶

**Review by gerred — APPROVED** [review]
yay lgtm!

**Pull request merged**
