### PR TITLE
bug: use correct config file path when loading all configs

### LINKED ISSUE #347: fix: API does not pick up GPU pods on cluster restart
Bug
The API does not pickup existing pods on cluster restart. vLLM, llamacpp, text-embeddings, etc.. leading to a restart of the API being necessary.

Expected
When a backend is running, the API will pick it up within a reasonable amount of time. This should include on cluster restart.

Reproduce
Restart a cluster with GPU backends. Once the cluster is back up and running, check the api's models endpoint to see if they are detected.

### PR DESCRIPTION
**Pull request by YrrepNoj**
Fixes #347

### CODE REVIEW

**Review by justinthelaw — DISMISSED** [review]

**Review by justinthelaw — COMMENTED** [review]
I think the pytests will need to be changed. Just curious as to why this changed? Seems like you are moving around the same info but just placing them in a different argument.

**Review by gerred — CHANGES_REQUESTED** [review]
tests

**Comment by YrrepNoj** [comment]
@gerred @justinthelaw 

PR updated to fix pytest

**Review by gerred — APPROVED** [review]
lgtm!

**Review by justinthelaw — APPROVED** [review]

**Pull request merged**
