### PR TITLE
chore(tests): Conformance testing templates

### PR DESCRIPTION
**Pull request by alekst23**
Creating and testing a template for performing Conformance testing between OpenAI and LeapfrogAI.

Tests require the following environment variables:
```
LEAPFROGAI_API_URL=https://leapfrogai-api.uds.dev/openai/v1
LEAPFROGAI_API_KEY=<your API key from supabase>
```

### CODE REVIEW

**Comment by alekst23** [comment]
In the current test set, all OpenAI tests pass. 

The following LFAI tests fail:
- Threads - create with message list. This requires modifications to the `threads` route or  `CreateThreadRequest`, to format the request message params into list of `MessageContent` types.
- Vector Stores - `client.beta.vector_stores.file_batches` is not implemented
- Vector Stores - file upload fails when file already exists:
```
File "/leapfrogai/.venv/lib/python3.11/site-packages/leapfrogai_api/backend/rag/index.py", line 60, in index_file                                 │
│     raise FileAlreadyIndexedError("File already indexed")
```

**Comment by alekst23** [comment]
TODO:
- Itemize all objects and methods for conformance testing
- - ([LeapfrogAI API Completeness](https://docs.google.com/spreadsheets/d/1eiIRgBIL57K9IqR2JKaj39Wkj_GXWNSMAW8NNjN6p2s/edit?gid=0#gid=0))
- Add all missing objects and methods to test bed

**Comment by alekst23** [comment]
All tests pass except the following LFAI endpoints:
- test_thread - threads.create with existing messages
- test_thread_file_annotations - annotation format, number of messages in runs

**Comment by gphorvath** [comment]
I'm glad to see these coming along! As a part of this PR you can probably remove the conformance testing I had started that is hanging out in the integration tests directory: https://github.com/defenseunicorns/leapfrogai/blob/b83ef045e9ea6305d811a847a2fed76ad1c4baa9/tests/integration/api/conformance_test.py

**Comment by justinthelaw** [comment]
Recommend merging with main, and also @gphorvath 's comment!

**Comment by alekst23** [comment]
Removed original conformance test file.
Merged main updates.

**Review by justinthelaw — APPROVED** [review]

**Pull request merged**
